<?php
include('../phps/configuracion.php');
$conn = pg_connect("host=".$host." port=".$puerto." user=".$usuario." dbname=".$dbname." password=".$password." ");

$nprestamo=$_GET['nprestamo'];//'2000003'; //$_GET['dni'];//'40700920'; //$_POST['dni'];

$query = pg_query("select idprestamo, idsocio, descripcion, tcuotas, mcuota, monto, plazo, comision,aporte, tea, tem, mora, tipopago, fprestamo, ftermino, fecpago, condicion, garantia, analista, recaudador, estado from tprestamo where nprestamo='". $nprestamo ."';");
$registros = pg_fetch_array($query, null, PGSQL_ASSOC);

$querys = pg_query("select concat(tipodoc,' ',numerodoc) as documento, concat(nombres,' ',apaterno,' ',amaterno) as socio, direccion from tsocio where idsocio='".$registros[idsocio]."';");
$registross = pg_fetch_array($querys, null, PGSQL_ASSOC);

$querya = pg_query("select concat(nombres,' ',apaterno,' ',amaterno) as analista from ttrabajador where idtrabajador='".$registros[analista]."';");
$registrosa = pg_fetch_array($querya, null, PGSQL_ASSOC);

$queryo = pg_query("select concat(nombres,' ',apaterno,' ',amaterno) as recaudador from ttrabajador where idtrabajador='".$registros[recaudador]."';");
$registroso = pg_fetch_array($queryo, null, PGSQL_ASSOC);

$html = '
	<h3><center>HOJA RESUMEN INFORMATIVA</center></h3>
	<h3><center>Nº '.$nprestamo.'</center></h3>
  	<p class=mayuscula> CONSTE POR EL PRESENTE DOCUMENTO DENOMINADO “HOJA RESUMEN INFORMATIVA” EL MISMO QUE FORMA PARTE DEL CONTRATO DE MUTUO DINERARIO SUSCRITO POR LAS PARTES, EL MISMO QUE TIENE POR FINALIDAD ESTABLECER LA TASA DE INTERÉS TANTO COMPENSATORIO COMO MORATORIO APLICABLE AL PRESTAMO OTORGADO, ASI MISMO LAS COMISIONES QUE, INTEGRA ASOCIADOS LTDA, EN ADELANTE DENOMINADO “INTEGRA ASOCIADOS” COBRARÁ A EL (LOS) SOCIO(S) POR LOS SERVICIOS QUE PROPORCIONE, Y LOS GASTOS EN QUE INCURRA CON TERCEROS DERIVADOS DE LAS OPERACIONES ACTIVAS, LOS MISMOS QUE SERAN TRASLADADOS AL SOCIO; ADEMÁS LA TASA Y EL MONTO DE TRIBUTOS QUE SE APLICARÁ POR LA OPERACIÓN, CONTIENE UN RESUMEN DE LAS OBLIGACIONES O FACULTADES CONTRACTUALES RELEVANTES PARA LAS PARTES DE ACUERDO A LOS SIGUIENTES DETALLES:
  	</p>

	<table class="tinformacion">
	<thead><tr><th colspan="4">DATOS DEL SOCIO</th></tr></thead>
	<tr><th width="100px">DOCUMENTO:</th><th width="250px">SOCIO(S):</th><th width="250px">DIRECCIÓN:</th><th width="80px">TIPO:</th></tr>
	<tr><td>'.$registross[documento].'</td><td>'.$registross[socio].'</td><td>'.$registross[direccion].'</td><td>TITULAR</td></tr>
	</table>	
	
	<table class="tinformacion">
	<thead><tr><th colspan="4">DATOS DEL PRESTAMO:</th></tr></thead>
	<tr><th width="175px">N° DE PRESTAMO:</th><th width="175px">PRÉSTAMO:</th><th width="175px">N° DE CUOTAS:</th><th width="175px">VALOR DE CUOTA:</th></tr>
	<tr><td>'.$nprestamo.'</td><td>'.$registros[descripcion].'</td><td>'.$registros[tcuotas].'</td><td> S/.'.$registros[mcuota].'</td></tr>
	<tr><th>MONTO DE PRESTAMO:</th><th>PLAZO:</th><th>COMISION:</th><th>APORTE x CUOTA:</th></tr>
	<tr><td>S/. '.$registros[monto].'</td><td>'.$registros[plazo].' Meses</td><td>S/. '.$registros[comision].'</td><td>S/. '.$registros[aporte].' x Mes</td></tr>
	<tr><th>TEA:</th><th>TEM:</th><th>INTERES MORATORIO:</th><th>TIPO PAGO:</th></tr>
	<tr><td>'.$registros[tea].' %</td><td>'.$registros[tem].' %</td><td>'.$registros[mora].' % x Día</td><td>'.$registros[tipopago].'</td></tr>
	<tr><th>FECHA DE PRESTAMO:</th><th>FRECUENCIA DE PAGO:</th><th>CONDICIÓN:</th><th>GARANTIA:</th></tr>
	<tr><td>'.$registros[fprestamo].'</td><td>'.$registros[fecpago].'</td><td>'.$registros[condicion].'</td><td>'.$registros[garantia].'</td></tr>
	<tr><th colspan="2">ANALISTA:</th><th colspan="2">RECAUDADOR:</th></tr>
	<tr><td colspan="2">'.$registrosa[analista].'</td><td colspan="2">'.$registroso[recaudador].'</td></tr>
	</table>
	<p class="mayuscula"> <b>1.LIQUIDACION ANTICIPADA Y PAGOS ADELANTADOS.</b>  EL (LOS) SOCIO(S) TIENE(N) DERECHO A EFECTUAR PAGOS ANTICIPADOS DE LAS CUOTAS O SALDOS EN FORMA TOTAL O PARCIAL, CON LA CONSIGUIENTE LIQUIDACIÓN DE INTERESES AL DÍA DE PAGO, REPROGRAMÁNDOSE EL SALDO DEL CRÉDITO. INTEGRA ASOCIADOS ACEPTA QUE EL (LOS) SOCIO(S) REALICE(N) EL PAGO TOTAL O PARCIAL DEL CRÉDITO ANTES DE SU VENCIMIENTO. EL (LOS) SOCIO(S) SOLO PAGARÁ(N) LOS INTERESES MENSUALES DEVENGADOS A LA FECHA DE PAGO INCLUYENDO LA COMISIÓN POR LA NUEVA LIQUIDACIÓN QUE EFECTÚA INTEGRA ASOCIADOS ANTE LA CANCELACIÓN ANTICIPADA, Y AMORTIZACIÓN PARCIAL DE CUOTAS.<br>
	<b>2. RESOLUCIÓN DE CONTRATO.</b>EN CASO DE INCUMPLIMIENTO: EN LA FECHA DE PAGO DE UNA O MAS CUOTAS ESTABLECIDAS EN EL CRONOGAMA DE PAGOS POR PARTE DE EL (LOS) SOCIO(S) CONFORME AL ARTÍCULO 1323° DEL CÓDIGO CIVIL, INTEGRA ASOCIADOS DARÁ POR VENCIDA TODAS LAS CUOTAS Y PROCEDERÁ A COMPLETAR EL PAGARÉ QUE SUSCRIBE DANDO INICIO AL COBRO JUDICIAL. EN CASO QUE EL PRÉSTAMO INGRESE AL ESTADO DE COBRANZA JUDICIAL, SERÁN DE CARGO DE EL (LOS) SOCIO(S) LOS GASTOS EN QUE INCURRIRÁ INTEGRA ASOCIADOS POR CONCEPTO DE HONORARIOS PROFESIONALES, INTERPOSICIÓN Y TRAMITACIÓN DEL PROCESO JUDICIAL. ASIMISMO, INTEGRA ASOCIADOS PODRÁ CONSIDERAR VENCIDOS TODOS LOS PLAZOS Y PROCEDER AL COBRO DEL ÍNTEGRO DE LO ADECUADO DE ACUERDO A LAS CLÁUSULAS ESTABLECIDAS EN EL CONTRATO DE PRÉSTAMO Y/O DOCUMENTOS ANEXOS.<br> 
	<b>3. TASA DE INTERÉS MORATORIO.</b> ES DE COMÚN ACUERDO QUE EN CASO EL (LOS) SOCIO(S) NO CUMPLAN  CON PAGAR SUS CUOTAS PERIÓDICAS EN LAS FECHAS ESTABLECIDAS EN EL CRONOGRAMA DE PAGOS ESTE(OS) INCURRIRÁ(N) DE MANERA INMEDIATA Y AUTOMÁTICA EN MORA, DE CONFORMIDAD CON LO PREVISTO POR EL ARTÍCULO 1333° DEL CÓDIGO CIVIL, SIN NECESIDAD DE REQUERIMIENTO O COMUNICACIÓN POR PARTE DE “INTEGRA ASOCIADOS” POR LO TANTO, LAS SUMAS NO CANCELADAS DEVENGARÁN, ADEMÁS DE LOS INTERESES COMPENSATORIOS, INTERESES MORATORIOS, A LA TASA ESTABLECIDA EN EL PRESENTE DOCUMENTO, Y SE CAPITALIZARÁN DIARIAMENTE.<br>
	<b>4. COMISIÓN POR COBRANZA MOROSA.</b> “INTEGRA ASOCIADOS” TIENE EL DERECHO DE COBRAR UNA COMISIÓN A EL (LOS) SOCIO(S) A PARTIR DEL TERCER DÍA DE ATRASO EN EL PAGO DE SUS CUOTAS CONFORME A LOS SIGUIENTES DETALLES: A) TRES NUEVOS SOLES PARA PRÉSTAMOS EN MONEDA NACIONAL, SIENDO APLICABLE DESDE EL QUINTO DÍA DE MORA HASTA EL DÍA OCHO, SIEMPRE Y CUANDO NO EXISTAN CUOTAS VENCIDAS, YA QUE EN ESTE CASO SE APLICARÁ LAS DISPOSICIONES ESTABLECIDAS EN EL CONTRATO DE PRÉSTAMO. B) CINCO NUEVOS SOLES PARA PRÉSTAMOS EN MONEDA NACIONAL A PARTIR DEL NOVENO DIA DE RETRASO EN EL PAGO DE LA CUOTA HASTA EL DÍA CATORCE; SIEMPRE Y CUANDO NO EXISTAN CUOTAS VENCIDAS. C) TRES POR CIENTO (3%) DEL MONTO DE LA CUOTA A PAGAR, APLICABLE DESDE EL DÍA 15 DE RETRASO EN EL PAGO DE LA CUOTA, HAST LA FECHA EFECTIVA DE PAGO Y SOBRE EL ELEGIBLE DE TODAS LAS CUOTAS PENDIENTES. EL IMPORTE MÍNIMO DE LA COMISIÓN DURANTE ESTE PERIODO ES DE DOCE NUEVOS SOLES PARA PRÉSTAMOS CONCEDIDO EN MONEDA NACIONAL. ESTA COMISIÓN SE APLICARA ADICIONALMENTE A LOS INTERÉSES MORATORIOS, COMISIONES POR NOTIFICACIONES DOMICILIARIAS DE ACUERDO AL TARIFARIO DE COMISIONES Y GASTOS VIGENTE, Y OTROS CARGOS POR CUENTA DE EL (LOS) SOCIO(S). ANTE EL INCUMPLIMIENTO DE EL (LOS) SOCIO(S) Y SUS GARANTES, SEGÚN LAS CONDICIONES PACTADAS, SE PROCEDERÁ A REALIZAR EL REPORTE CORRESPONDIENTE A LA CENTRAL DE RIESGOS CON LA CALIFICACIÓN QUE CORRESPONDA, DE ACUERDO A LAS RESOLUCIONES DE LA SUPERINTENDENCIA DE BANCA Y SEGUROS.<br>
	<b>5. CAPITALIZACIÓN DE COMISIONES, INTERESES, MORAS OTROS CARGOS.</b> LOS INTERES COMPENSATORIOS TANTO COMO EL INTERÉS MORATORIO, LA COMISIÓN DE CRÉDITO, OTRAS COMISIONES, EL SEGURO DE DESGRAVAMEN, COSTOS DE NOTIFICACIONES DOMICILIARIAS, COSTOS Y COSTAS DEL PROCESO JUDICIAL Y OTROS CARGOS POR CUENTA DE EL (LOS) SOCIO(S) SE CAPITALIZARÁN.<br>
	<b>6. OBLIGACIONES DE LOS FIADORES SOLIDARIOS Y/O GARANTES.</b> LOS FIADORES SOLIDARIOS Y/0 GARANTES SE OBLIGAN ANTE “INTEGRA ASOCIADOS” EN FORMA SOLIDARIA, IRREVOCABLE, INCONDICIONADA, LIMITADA E INDEFINIDA, RENUNCIANDO EXPRESAMENTE AL BENEFICIO DE EXCUSIÓN, OBLIGÁNDOSE A PAGAR TODAS LAS OBLIGACIONES DE EL (LOS) SOCIO(S) CONTRAÍDAS EN EL CONTRATO DE CRÉDITO DE MUTUO DINERARIO Y EN ESTE DOCUMENTO, ACEPTANDO DESDE YA CUALQUIER MODIFICACIÓN A LAS CONDICIONES DEL CRÉDITO QUE GARANTIZAN, ACEPTANDO TODAS LAS PRÓRROGAS DE LOS PLAZOS ESTABLECIDOS EN EL CONTRATO DE CRÉDITO QUE “INTEGRA ASOCIADOS” QUEDA FACULTADA A CONCEDER.<br>
	<b>7. OTRAS DISPOCISIONES ESPECIALES.</b><br>
	7.1 EL (LOS) SOCIO(S) AUTORIZA(N) EXPRESAMENTE A “INTEGRA ASOCIADOS” A REALIZAR LOS CARGOS EN CUALQUIERA DE SUS CUENTAS, RETENER FONDOS, APLICARLOS A SUS DEUDAS O CRÉDITOS, SEAN DIRECTOS O INDIRECTOS, PENDIENTES DE PAGO CON “INTEGRA ASOCIADOS” CUALQUIER SUMA DE DINERO O VALOR QUE “INTEGRA ASOCIADOS” TENGA EN SU PODER, ASI COMO LA EJECUCIÓN DE LOS DEPÓSITOS DADOS EN GARANTIA POR CRÉDITOS DIRECTOS E INDIRECTOS, A PARTIR DEL DÍA QUINCE (15) DE ATRASO, EN EL CASO DE QUEDAR SALDO A FAVOR DEL SOCIO, SE DEPOSITARÁ EN UNA CUENTA, LUEGO DE LA COMPENSACIÓN.<br>
	7.2 EL (LOS) SOCIO(S) AUTORIZAN EXPRESAMENTE A “INTEGRA ASOCIADOS” A REALIZAR LA EJECUCIÓN MEDIANTE REMATE O ADJUDICACIÓN DE LOS BIENES OTORGADOS EN PRENDA EN CASO DE INCUMPLIMIENTO.<br>
	7.3 EL (LOS) SOCIO(S) PRESENTA(N) COMO GARANTÍA UN PAGARÉ FIRMADO DE ACUERDO A LA LEY DE TÍTULOS Y VALORES VIGENTES; EN CASO DE INCUMPLIMIENTO DEL SOCIO, LA EMPRESA PODRÁ INICIAR LAS ACCIONES LEGALES QUE COORESPONDAN CONTRA LA GARANTÍA PRESENTADA Y OTORGADA POR EL SOCIO, GARANTES Y/O FIADORES; HASTA CUBRIR EL IMPORTE DE LOS INTERES MORATORIOS Y COMPENSATORIOS, COMISIONES, GASTOS Y COSTAS DEL PROCESO DE COBRANZA Y EL MONTO DE CRÉDITO.<br>
	7.4 EL (LOS) SOCIOS Y SU(S) FIADOR(ES) SOLIDARIO(S) DECLARAN EXPRESAMENTE QUE INTEGRA ASOCIADOS HA PUESTO DE SU CONOCIMIENTO LOS MECANISMOS DE PROTECCIÓN QUE LA LEY PERMITE PARA LA EMISIÓN O ACEPTACIÓN DE TÍTULOS VALORES INCOMPLETOS. HABIENDO SIDO PLENAMENTE INFORMADOS DE LOS ALCANCES DEL ARTÍCULO 10° DE LA LEY N° 27287 – LEY DE TÍTULOS Y VALORES.<br>
	7.5 LOS TÉRMINOS Y CONDICIONES ESTABLECIDAS EN LA PRESENTE HOJA RESUMEN, EL CONTRATO DE MUTUO DINERARIO, EL CRONOGRAMA DE PAGOS Y/O DOCUMENTOS ANEXOS PODRÁN SER AMPLIADOS, MODIFICADOS, RESTRINGIDOS O SUPRIMIDOS UNILATERALMENTE POR “INTEGRA ASOCIADOS”, COMUNICÁNDOLO MEDIANTE PUBLICACIÓN EN SU PÁGINA WEB, AVISOS COLOCADOS EN LAS OFICINAS DE ATENCIÓN AL PÚBLICO U OTRO TIPO DE COMUNICACIÓN MASIVA O DE INFORMACIÓN PERMITIDA POR LAS NORMAS DE TRANSPARENCIA DE LA INFORMACIÓN AL USUARIO. NO OBSTANTE, AQUELLAS QUE ESTÉN REFERIDAS A LAS TASAS DE INTERÉS, COMISIONES, GASTOS DETALLADOS, SERÁN COMUNICADOS PREVIAMENTE A EL (LOS) SOCIO(S) Y DENTRO DE LOS PLAZOS PREVISTOS, MEDIANTE CORRESPONDENCIA DIRIGIDA A SU DOMICILIO Y OTRO MEDIO SEÑALADO POR EL CONTRATO DE PRÉSTAMO. AQUELLAS CONDICIONES QUE IMPLIQUEN CONDICIONES MÁS FAVORABLES PARA EL SOCIO SE APLICARÁN AUTOMÁTICAMENTE.<br>
	<b>DECLARACIONES Y FIRMAS.</b> EL (LOS) SOCIO(S) Y LOS FIADORES SOLIDARIOS Y/O GARANTES DECLARAMOS HABER LEÍDO PREVIAMENTE Y RECIBIDO EL CONTRATO DE MUTUO DINERARIO, LA HOJA RESUMEN INFORMATIVA, EL TARIFARIO DE COMISIONES Y/O GASTOS VINCULADOS A OPERACIONES ACTIVAS, CRONOGRAMA DE PAGOS, COPIA DEL PAGARÉ  Y QUE HEMOS SIDO INSTRUIDOS ACERCA DE LOS ALCANCES Y SIGINIFICADO DE LOS TÉRMINOS Y CONDICIONES ESTABLECIDOS EN DICHOS DOCUMENTOS, HABIENDO SIDO ABSUELTAS Y ACLARADAS A NUESTRA SATISFACCIÓN  TODAS LAS CONSULTAS EFECTUADAS Y/O DUDAS, POR LO QUE SUSCRIBIMOS EL PRESENTE DOCUMENTO EN DUPLICADO Y CON PLENO CONOCIMIENTO DE LAS CONDICIONES ESTABLECIDAS EN DICHOS DOCUMENTOS.
	</p>
	<table class="datos">
		<tr><td width="100px"></td><td class="firma"></td><td width="100px"></td><td class="huella"></td><td></td></tr>
		<tr><td></td><td style="text-align: center;">FIRMA DEL SOCIO</td><td></td><td>HUELLA DIGITAL</td><td></td></tr>
		<tr><td></td><td>Nombre: '.$registross[socio].'</td><td></td><td></td><td></td></tr>
		<tr><td></td><td>Documento: '. $registross[documento].'</td><td></td><td></td><td></td></tr>
	</table>';

//==============================================================
//==============================================================
//==============================================================

include("mpdf/mpdf.php");

//new mPDF($mode, $format, $font_size, $font, $margin_left, $margin_right, $margin_top, $margin_bottom, $margin_header, $margin_footer, $orientation);
$mpdf=new mPDF('c','A4');

$mpdf->SetDisplayMode('fullpage');

// LOAD a stylesheet
$stylesheet = file_get_contents('formatoA4.css');
$mpdf->WriteHTML($stylesheet,1);	// The parameter 1 tells that this is css/style only and no body/html/text

$header = '<table width="100%" style="border-bottom: 1px solid #000000; vertical-align: bottom; font-family: serif; font-size: 9pt; color: #000088;"><tr>
<td style="text-align: left;"><img src="logoia.gif"></td>
</tr></table>';

$footer = '<table width="100%" style="border-top: 1px solid #000000; vertical-align: top; font-family: serif; font-size: 8pt; color: #000088;"><tr>
	<td style="text-align: center;">AV. Manuel Callo Zevallos Nº 444 - Telf. 084 - 211602 <br> Distrito de Sicuani, Provincia de Canchis y Departamento del Cusco.</td>
</tr></table>';


$mpdf->setAutoTopMargin = 'stretch';
$mpdf->setAutoBottomMargin = 'stretch';

$mpdf->SetHTMLHeader($header);
$mpdf->SetHTMLFooter($footer);


$mpdf->WriteHTML($html);

$mpdf->Output();

exit;
//==============================================================
//==============================================================
//==============================================================

?>